version: '2'
services:
    meetapp-app:
        image: meetapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://meetapp-mysql:3306/meetapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meetapp-mysql:
        extends:
            file: mysql.yml
            service: meetapp-mysql
